name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Fixed cron expression
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg
          gif_out_path: dist/snake.gif  # Optional: also generate GIF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4  # Updated to v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}